version: "3"

services:
  zoo:
    image: cfei/zookeeper:1.1.0
    container_name: zoo
    restart: on-failure
    ports:
      - 2181:2181
    environment:
      ZOO_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888

  kafka:
    image: cfei/kafka:2.0.0-beta
    container_name: kafka
    restart: on-failure
    ports:
      - 9091:9091
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo:2181/kafka
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER_LISTENER:PLAINTEXT"
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9091,EXTERNAL://0.0.0.0:9092,DOCKER_LISTENER://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:9091,EXTERNAL://${HOST_DNS}:9092,DOCKER_LISTENER://kafka:19092"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_HEAP_OPTS: "-Xmx${KAFKA_RAM}G"
      KAFKA_HEALTHCHECK_PORT: 9091
    depends_on:
      - zoo

# Wesley
  wesley-mysql:
    image: mysql
    container_name: wesley-mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: 532c5b0a-2cd9-4eed-ad10-6dcdea6e732b
      MYSQL_USER: archiver
      MYSQL_PASSWORD: c0d9f4f4-f978-4ff3-98a7-8a30a182bbd9
      MYSQL_DATABASE: metadata
    # volumes:
    #   - ./containervolumes/wesley-mysql:/var/lib/mysql

  cassandra1:
    image: cassandra
    container_name: cassandra1
    restart: on-failure
    environment:
      CASSANDRA_SEEDS: cassandra1,cassandra2
    # volumes:
    #   - ./containervolumes/cassandra1/data:/opt/cassandra/data

  cassandra2:
    image: cassandra
    container_name: cassandra2
    restart: on-failure
    environment:
      CASSANDRA_SEEDS: cassandra1,cassandra2
    # volumes:
    #   - ./containervolumes/cassandra2/data:/opt/cassandra/data

  wesley:
    image: cfei/wesley:0.3
    container_name: wesley
    restart: on-failure
    environment:
      KAFKA_SUBDB: /var/log/wesley/kafka_subscriptions.txt
      KAFKA_BROKERS: kafkaf:9092
      KAFKA_GROUP: uniten_archiver
      KAFKA_PREFIX: uniten_archiver
      MYSQL_HOST: wesley-mysql
      MYSQL_PORT: 3306
      MYSQL_USER: archiver
      MYSQL_PASSWORD: "${WESLEY_MYSQL_PASSWORD}"
      MYSQL_DATABASE: metadata
      CASSANDRA_HOSTS: cassandra1,cassandra2
      CASSANDRA_PORT: 9042
      CASSANDRA_KEYSPACE: data
      CASSANDRA_TABLE_PREFIX: prefix_is_currently_hardcoded
    volumes:
      - ./containervolumes/wesley-logs:/var/log/wesley
    depends_on:
      - wesley-mysql
      - cassandra1
      - cassandra2
      - kafka